# Generated by Django 4.2 on 2024-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_state', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
                ('conetent', models.TextField()),
                ('image', models.ImageField(upload_to=None, verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
