# Generated by Django 4.2 on 2024-05-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_poduct_product_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='conetent',
            new_name='content',
        ),
    ]
