# Generated by Django 4.2 on 2024-05-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='username',
        ),
    ]
